### ISSUE TITLE
How to detect the networks down when uploading and downloading

### ISSUE THREAD

**Issue by mt-lelang** [dropbox/dropbox-sdk-obj-c#192]
I could not know how to detect when networks down when uploading and downloading.

```
[[[client.filesRoutes downloadData:@"/test/path/in/Dropbox/account/my_file.txt"]
    setResponseBlock:^(DBFILESFileMetadata *result, DBFILESDownloadError *routeError, DBRequestError *networkError,
                       NSData *fileContents) {
      if (result) {
        NSLog(@"%@\n", result);
        NSString *dataStr = [[NSString alloc] initWithData:fileContents encoding:NSUTF8StringEncoding];
        NSLog(@"%@\n", dataStr);
      } else {
        NSLog(@"%@\n%@\n", routeError, networkError);
      }
    }] setProgressBlock:^(int64_t bytesDownloaded, int64_t totalBytesDownloaded, int64_t totalBytesExpectedToDownload) {
  NSLog(@"%lld\n%lld\n%lld\n", bytesDownloaded, totalBytesDownloaded, totalBytesExpectedToDownload);
}];
```

**Comment by greg-db** [comment]
For upload/download calls like this, you won't necessarily get a `DBRequestError` if you lose the connection, since that uses a background session which will just automatically resume when the connection returns. (Non-upload/download calls will return a `DBRequestError` though.)

If you want to proactively check for a network connection, you can use [`Reachability`](https://developer.apple.com/library/content/samplecode/Reachability/Introduction/Intro.html).
