### ISSUE TITLE
key-chain authorization issue not resolved with current solution 

### ISSUE THREAD

**Issue by igiso** [dropbox/dropbox-sdk-obj-c#200]
I noticed that - in our main app, the keychain bug - persists even though we enabled the keychain sharing in capabilities.

The behavior we see on the simulator is the app running the log in dialog every-time it lunches (asking for email and password and then allow)

and on the actual device, every-time we launch the app the dropbox app is lunched asking to allow authorization

for some reason it doesn't remember the authorization 

I've studied the documentation very closely I am not sure what part is missing.

*worth to. notice that we are writing in objective - C++ and not objective C
meaning that we wrap the dropbox client into a c++ class

but it shouldn't make any difference, unless there is a callback from somewhere that is not registered properly ?

I am curious to hear your thoughts on this issue

**Comment by greg-db** [comment]
Are you referring to the keychain bug [noted here](https://github.com/dropbox/dropbox-sdk-obj-c#xcode-8-and-ios-10-bugs)? That's supposed to only affect simulators, not devices. You mentioned you're having the issue with devices too, so that may not be related.

If you've set up the authorization flow [as documented](https://github.com/dropbox/dropbox-sdk-obj-c#handling-the-authorization-flow), the client should be accessible later via `authorizedClient`. If that's not working for you, can you share the version number of the SDK you're using, and the relevant code snippets? Thanks in advance!

**Comment by igiso** [comment]
yes that is the Issue,  - I also agree is not exactly the same.
 in the dbroulette example the "fix" works.

but in our own project it doesn't 
 
<img width="877" alt="screen shot 2017-11-17 at 09 47 07" src="https://user-images.githubusercontent.com/2058400/32936297-67411264-cb7c-11e7-9a12-362b98c0bacf.png">



When do we access the key-chain? is it up to us to handle this or the API is supposed to do it automatically

**Comment by greg-db** [comment]
You should check `authorizedClient` to see if you already have a client available based on an access token stored in the keychain, i.e., before calling `authorizeFromController`. Are you doing so? (I don't see it in the portion of the code you shared.)

You can see how [the example app uses that to update the UI here](https://github.com/dropbox/dropbox-sdk-obj-c/blob/003d03898d77052f5958938363be0b98e9088618/Examples/DBRoulette/iOS/CocoaPodsProject/DBRoulette/DBRoulette/ViewController.m#L58).

**Comment by igiso** [comment]
Yes you are correct, I missed that part - checking before authorizing solved the issue.

Thank you 👍  🥇 🍺
