### ISSUE TITLE
How to share an uploaded file that the server auto-renamed?

### ISSUE THREAD

**Issue by xaphod** [dropbox/dropbox-sdk-obj-c#21]
Sorry if I overlooked something obvious... 
I need to upload a file and then share it.  Sounds simple but not when server-renaming is desired & switched on.

Steps:
1. I upload a file, with the policy that the server should rename if there is a collision (there's a high chance there will be a collision in this app, so renaming is necessary)
2. In the return of uploadURL, I only get a `DBFILESFileMetadata`, which doesn't contain what the server actually named the file. So there is no way to determine if the server has renamed the file, so I cannot use the `path` as input to the share command. I can see `DBFILESFileMetadata.id_`, but I cannot see how to use `id_` to init anything useful. 

How can I share a file that i've uploaded that the server renamed?

thx

**Comment by greg-db** [comment]
@xaphod The returned metadata should be for the actual resulting file, including the potentially renamed name. I just tried this out and confirmed it's working for me.

One thing to watch out for though is if you're uploading the same exact data as already exists at the path, that won't be considered a conflict (since nothing changed), and so a new/renamed file won't be created.

To answer the rest of your question though, you can pass a file ID in place of file path in some places, like this:
```
[client.filesRoutes getMetadata:result.id_]
```

**Comment by xaphod** [comment]
Ahhh -- I had just somehow missed that `DBFILESFileMetadata` was a subclass of `DBFILESMetadata`, which exposes name. And I probably wouldn't have guessed that the name property there will change based on server doing autorenaming, thanks for the help there.
Yup, it works! thanks.
