### ISSUE TITLE
DBCOMMONRootInfo does not contain 'home_path' property which is described in the documentation

### ISSUE THREAD

**Issue by apodrugin** [dropbox/dropbox-sdk-obj-c#246]
According to the documentation (https://www.dropbox.com/developers/reference/namespace-guide) 'root_info' dictionary contains 'home_path' property. This property is present in JSON response, but it is not parsed and is missed in the DBCOMMONRootInfo interface.

**Comment by greg-db** [comment]
[The `homePath` field](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBCOMMONTeamRootInfo.html#/c:objc(cs)DBCOMMONTeamRootInfo(py)homePath) is only set on [`DBCOMMONTeamRootInfo`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBCOMMONTeamRootInfo.html), not [`DBCOMMONUserRootInfo`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBCOMMONUserRootInfo.html) or [`DBCOMMONRootInfo`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBCOMMONRootInfo.html) itself. 

[`DBCOMMONTeamRootInfo`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBCOMMONTeamRootInfo.html) and [`DBCOMMONUserRootInfo`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBCOMMONUserRootInfo.html) both inherit from [`DBCOMMONRootInfo`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBCOMMONRootInfo.html), and correspond to the "team" and "user" tags shown in [the Namespace Guide](https://www.dropbox.com/developers/reference/namespace-guide), respectively.

You'll only get a [`DBCOMMONTeamRootInfo`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBCOMMONTeamRootInfo.html) if the user is on a team using a "[team space](https://help.dropbox.com/business/team-space-overview)". Otherwise, there isn't a `home_path`.

Which type are you getting? If you are somehow getting a [`DBCOMMONTeamRootInfo`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBCOMMONTeamRootInfo.html) in particular without a `homePath`, please share the output here so we can investigate. Thanks!

**Comment by apodrugin** [comment]
Thank you for your response! I have missed that DBCOMMONRootInfo has subclasses, because DBUSERSFullAccount exposes 'rootInfo' property with DBCOMMONRootInfo return type and it is not mentioned in documentation in code that it may return instances of the subclasses with additional information. So, the right way to get home_path is to check that 'rootInfo' is actually DBCOMMONTeamRootInfo class and cast to it? Am I right?

**Comment by greg-db** [comment]
That's correct, you'd need to check and cast the type in order to access that type-specific `homePath` property. That would look something like this:

    [[client.usersRoutes getCurrentAccount] setResponseBlock:^(DBUSERSFullAccount *account, DBNilObject *_, DBRequestError *error) {
        if (account) {
            
            if ([account.rootInfo isKindOfClass:[DBCOMMONTeamRootInfo class]]) {
                DBCOMMONTeamRootInfo *teamRootInfo = (DBCOMMONTeamRootInfo *)account.rootInfo;
                NSLog(@"%@", teamRootInfo);
                NSLog(@"%@", teamRootInfo.homePath);
            } else if ([account.rootInfo isKindOfClass:[DBCOMMONUserRootInfo class]]) {
                DBCOMMONUserRootInfo *userRootInfo = (DBCOMMONUserRootInfo *)account.rootInfo;
                NSLog(@"%@", userRootInfo);
            }
            
        } else if (error) {
            NSLog(@"%@", error);
        }
    }];

Please let me know if that works as expected for you. Thanks!

**Comment by apodrugin** [comment]
I have checked it in my environment. Everything works as expected. Thank you!
