### ISSUE TITLE
[Catalyst] Support UIKitForMac

### ISSUE THREAD

**Issue by chrisvanbuskirk** [dropbox/dropbox-sdk-obj-c#247]
When attempting to create a dropbox connection with an iPad app for the Mac, I receive these errors.

```
2019-06-10 07:47:02.452516-0600[2516:151619] -canOpenURL: failed for URL: "dbapi-2://1/connect" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
2019-06-10 07:47:02.453821-0600 [2516:151619] -canOpenURL: failed for URL: "dbapi-8-emm://1/connect" - error: "The operation couldn’t be completed. (OSStatus error -10814.)"
```

Obviously, dropbox should probably already use an account created on the Mac already, or then start a authentication process.

**Comment by greg-db** [comment]
Thanks for the post! The Dropbox macOS application doesn't support the same native app authorization flow that the Dropbox iOS app does. I'll pass this along as a feature request, but I can't promise if or when that might be implemented. 

That means that those '10814' errors are expected on macOS, as they indicate that the official Dropbox iOS app isn't installed, so the app authorization flow is sent through Safari instead (specifically via `SFSafariViewController`). 

Can you confirm if that fallback is working and you can process the app authorization flow via the web site?

**Comment by chrisvanbuskirk** [comment]
Safari is not opened when it fails.

**Comment by greg-db** [comment]
Thanks for following up. To clarify though, are you saying you are not able to process the app authorization flow at all when using this SDK in an iPad app for the Mac? 

We haven't tested this SDK with Catalyst yet, but the desired/expected behavior, to match the current behavior on iOS, would be to have the Dropbox app authorization page presented in `SFSafariViewController` (not Safari.app itself) so the user can authorize the app there. 

If that's not working at all, please confirm so we can look into it. Please let me know what, if anything, does happen, including any other errors/output you may get in addition to the output you shared in the first message. Thanks in advance!

**Comment by chrisvanbuskirk** [comment]
No, that is not working.  Nothing is opened and I just receive that error in the console.

**Comment by chrisvanbuskirk** [comment]
As a sanity check, I tested in my app.  The controller is brought up with dropbox is missing from the device.

![Image-1](https://user-images.githubusercontent.com/3638007/59211732-d56e9100-8b6d-11e9-8b0c-0db18213936c.jpeg)

**Comment by greg-db** [comment]
Got it, thank you for confirming that. I'll ask the team to look into this to see if we can get this working.

**Comment by greg-db** [comment]
@chrisvanbuskirk Can you try again with the latest macOS 10.15 beta? (I believe it's 19A487I). It looks like the behavior on this may have changed so I just want to check you're seeing the same thing. (It doesn't appear to be fully fixed, but it does now at least open the page in Safari for me.) Thanks!

**Comment by chrisvanbuskirk** [comment]
@greg-db Sorry it took so long, but I have confirmed the fix.
