### ISSUE TITLE
can not upload file

### ISSUE THREAD

**Issue by kotercy** [dropbox/dropbox-sdk-obj-c#279]
sorry.I am newbie ti drop box. i have a problem but I do not to know how to deal with it. my problem
 must not a issues,apologies! the detail is below
I downloaded the source code and build as a framework.when  touch the button in the interface titled"loginDropbox" to login,the console print :Success! User is logged into Dropbox.!then touch the button titled "upload file",in the task callback ,I received  a error;
**Error Domain=NSURLErrorDomain Code=-1003 \"A server with the specified hostname could not be found.**
the upload source code and error information is in attach file
<img width="1181" alt="截屏2020-09-25 下午3 26 58" src="https://user-images.githubusercontent.com/17897001/94238969-aab37200-ff43-11ea-99c6-e1ba39edd63e.png">
Best regards!

**Comment by kotercy** [comment]
Xcode version Version 12.2 beta (12B5018i) macOS app,use the sample code DBRoulette is fetch list successfully. I do not why.but DBRoulette has a parent folder named "CarthageProject".is this influence?

**Comment by greg-db** [comment]
From the error output, it looks like this failure is due to a DNS issue. Specifically, it looks like your device wasn't able to resolve the hostname used for Dropbox API upload calls, which is `api-content.dropbox.com` in this case.  

This hostname is currently resolving correctly though, so you'll need to troubleshoot your setup to see why your device isn't able to perform this lookup. For example, is there any software that may be interfering with this, such as a firewall, proxy, etc.? Otherwise, you may need to check that your DNS server is working properly.

**Comment by kotercy** [comment]
need to close the sandbox in target.then worked.thank you !
