### ISSUE TITLE
Migrating from v1 to v2 API

### ISSUE THREAD

**Issue by Dejal** [dropbox/dropbox-sdk-obj-c#30]
I'm working on migrating a Mac project from the v1 to v2 API, and finding it slow going.  The API has changed significantly, with the v2 more complex and hard to find documentation and examples.

These are issues I have currently; I'd appreciate advice (and enhancements if missing functionality):

1. With the v1 API, I used the following call to load metadata only for files that had changed since the previous invocation, using a hash.  I don't see any option for that in v2?

    `[delegate.restClient loadMetadata:dropboxFolderPath withHash:hash];`

2. The response from the above included a `lastModifiedDate` property for each item.  I see that is available in the debug description of `DBFILESMetadata`, but I don't see a property for it (either as a string or `NSDate`).

3. With v1 I used the following call to get a sharing link, with a flag for a short URL or full URL.  I don't see an option for a short URL when calling `createSharedLinkWithSettings`, or any other way to get one?

    `[delegate.restClient loadSharableLinkForFile:dropboxFilePath shortUrl:shortURL];`

4. With v1 I used the following to get a direct link to a document.  I don't see an equivalent method in v2, unless that is `getTemporaryLink`?

    `[delegate.restClient loadStreamableURLForFile:dropboxFilePath];`

I'd appreciate assistance with these!

**Comment by rodionovd** [comment]
Hi @Dejal! While I'm not one of the authors of this SDK I've played a little bit with it today and here's what I found out:

> With the v1 API, I used the following call to load metadata only for files that had changed since the previous invocation, using a hash. I don't see any option for that in v2?

They basically renamed *hash* to *cursor* in V2, so what you need is `-listFolderContinue:` method of the SDK. See the [docs](https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder-continue) for details.

> The response from the above included a lastModifiedDate property for each item. I see that is available in the debug description of DBFILESMetadata, but I don't see a property for it (either as a string or NSDate).

The thing is that `DBFILESMetadata` is an abstract class (think of a protocol) and what you actually receive in completion handlers is either `DBFILESFileMetadata` or `DBFILESFolderMetadata` or `DBFILESDeletedMetadata` for files, directories and deleted items respectively (use [`-isKindOfClass:`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Protocols/NSObject_Protocol/index.html#//apple_ref/occ/intfm/NSObject/isKindOfClass:) to figure this out). The first one does contain `clientModified` and `serverModified` properties.

I hope that this fact would be clarified somewhere in the docs // cc @scobbe 

Hope this helps!

**Comment by greg-db** [comment]
Thanks Dmitry, and thanks for the feedback on the docs!

For reference, there is a section on using `is<TAG_STATE>` methods here:

https://github.com/dropbox/dropbox-sdk-obj-c#handling-responses-and-errors

To fill in the rest of the answers:

3) Getting a shared link with a short URL via API v2 is only available via the deprecated [`-createSharedLink:shortUrl:pendingUpload:`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBSHARINGRoutes.html#/c:objc(cs)DBSHARINGRoutes(im)createSharedLink:shortUrl:pendingUpload:).

4) Yes, `getTemporaryLink` is the equivalent of `loadStreamableURLForFile`.

**Comment by rodionovd** [comment]
@greg-db you're right: there's a section in the docs about this, but "unions" and "structs" are very uncommon in Objective-C, so I find it hard to wrap my head around them.

Take, for instance, this sentence:

> Struct types are "traditional" object types

**Comment by rodionovd** [comment]
@greg-db you're right: there's a section in the docs about this, but "unions" and "structs" are very uncommon in Objective-C, so I find it hard to wrap my head around them.

Take, for instance, this sentence:

> Struct types are "traditional" object types

Well, I (personally) can't see how a struct type can be an object (aka a reference type) at the same time. Sure, Objective-C doesn't have first-class struct types (unlike Swift) but it still doesn't make sense to call plain objects structs. 

One more thing that's hard for me to understand is this:

> This Metadata object is known as a "datatype with subtypes" in our API v2 documentation. The difference between these "datatypes with subtypes" and union types is that union types can exist as only one instance value at a time, whereas these "datatypes with subtypes" can exist as multiple instance values at a time.

It's not clear what "one instance value at a time" and "multiple instance values at a time" mean. I understand that inheritance is somehow related here, but it's still very obscure way of saying it in my opinion. Can you please elaborate on this one?

**Comment by Dejal** [comment]
Thanks for the answers to my questions.

Re `-createSharedLink:shortUrl:pendingUpload:`, please add a non-deprecated method that includes a short URL option.

For what it's worth, I think the API design is overly complex, and really not a good fit for ObjC and Cocoa standards.  I understand that it's machine-converted from a non-native API, so your options are limited.  I just wanted to provide feedback that I expect many ObjC developers to struggle with this.  Documentation improvements and more examples may help.

**Comment by scobbe** [comment]
@rodionovd: Thanks for reaching out. I can try and update the documentation to make it a little clearer. Let me know if this explanation makes more sense.

First off, the "structs" and "unions" terminology is specific to our API, and not to any of the languages that are used to query our API, so I would avoid thinking of them in terms of their Objective-C definition.

"Struct" in our API context is not about value vs reference, it's about existing statically as one object type (with zero, one, or more than one associated instance values). In other words, regardless of runtime state, my "struct" object – let's use an example from our API and call it `CreateFolderArg` – is going to always be the same type, in this case, `CreateFolderArg`. There is no need to check a "tag" at runtime to see if exists as a different type. This is the straightforward object paradigm that we're all used to dealing with.

"Union" in our API context is about single values that can exist as a number of different types. We capture all of these different type scenarios under one "union object", but that object will only exist as one type at runtime. This is where we check the object's "tag" to see what type it currently exists as (it might be a "void" type, in which case, it is used merely as a sentinel value and has no associated value with it).

"Datatypes with subtypes" are a way combining structs and unions. Datatypes with subtypes are struct objects that contain a tag, which specifies which subtype the object exists as at runtime. The reason we have this construct, as with unions, is so we can capture a multitude of scenarios with one object. For example, some of our endpoints return a `Metadata` type. This `Metadata` type can exists as `FileMetadata`, `FolderMetadata` or `DeleteMetadata`. Each of these types have common instances values like "name" (the name for the file, folder or deleted type). In order to leverage inheritance, we set a common super type called `Metadata` which has all of the common instance values, but also has a tag instance value, which specifies which additional subtype-specific instance values the object will have. In this way, "datatypes with subtypes" are a hybrid of structs and unions.

Does this clear things up at all?

**Comment by rodionovd** [comment]
@scobbe thanks for clarification! I wasn't aware that this is your API terminology, so that was the root cause of my miscommunication with the docs I guess.

Unfortunately I think that I'm not alone here and there will be other Objective-C developers who will try to figure out what this terminology means in terms of this particular language and programming patterns that are common in Cocoa. After all, this is an Objective-C SDK, right? :-)

I understand that it may sound inefficient to use different wording just in this one SDK but I believe that it would help users a ton: they may not be familiar with your API but they are familiar with the platform they develop software for.

Once again, thanks for making things clear and have a nice day!  ❤️
