### ISSUE TITLE
How to check which file is latest local or the one inside dropbox folder?

### ISSUE THREAD

**Issue by Prarik** [dropbox/dropbox-sdk-obj-c#38]
I am working on project where I have to upload/download files between my iOS device and dropbox folder. 

Now I have a file named **"Filename.txt"** in my iOS app as well as in my dropbox folder.

How do I check which one is latest copy? 

In dropbox api v1 there was a property called **"revision" = "123"** which was number and now that is deprecated and a new property called **"rev" = "f30099771a"** is there but I can't figure it out how to use that.

Please someone help.

Thanks in advance.

**Comment by greg-db** [comment]
Hi @Prarik the `rev` value you mentioned is what you should use. You should store the `rev` of the file when you download a copy. Later, you can compare that stored value against the one reported in the API for the metadata for that file. If the value is different, you know that the file changed and so you should download the new version, if you want.

**Comment by Prarik** [comment]
Hello @greg-db thanks for the quick response. Wow really fast!!! and thanks again for providing Objective C version of this api.

**Filename = “Employee.txt”**

 Let’s say “rev” by default is “Empty” when I create my file in iOS device, I come to sync and check for empty that means I will upload that file to dropbox as that file does not exist on dropbox yet.

Now once file is uploaded I set “rev” property of local iOS file “Employee.txt” same as dropbox file.

After some time I made some changes to “Employee.txt” file and save it.

Now when I try to sync that file to dropbox how do I know which file version is the latest one? and I need to delete the server copy and replace the local file with the server file as both file has same “rev” property.

Now same problem occurs when I change server copy of change file from another iOS device.

**Comment by greg-db** [comment]
I wouldn't recommend relying on the concept of "latest", since that's not reliable. (E.g., different devices may have different clock skew, etc.) 

Instead, when you make a local change to the local file, you upload the new version of the file, e.g., using [-uploadUrl:mode:autorename:clientModified: mute:inputUrl:](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESRoutes.html#/c:objc(cs)DBFILESRoutes(im)uploadData:mode:autorename:clientModified:mute:inputData:). You should supply an "update" [`DBFILESWriteMode`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESWriteMode.html#/c:objc(cs)DBFILESWriteMode(im)initWithUpdate:) with the `rev` value that you based that update on.

If the `rev` you supply is correct, that is, it's a change to the version of the file on the server, the upload is accepted and overwrites the server's copy. If value isn't correct though, e.g., if another device uploaded another version at the same time, a conflict file is created instead (subject to the `autorename` parameter).

That way, the user/app can resolve conflicts manually if/when they happen, without losing either new version of the file. 

There's more information in the documentation I linked to above, so I recommend reading through that to understand exactly how that works and choose how you want to program your app.
