### ISSUE TITLE
Pod don't support ObjectiveDropboxOfficial

### ISSUE THREAD

**Issue by Moussy** [dropbox/dropbox-sdk-obj-c#44]
pod search ObjectiveDropboxOfficial
[!] Unable to find a pod with name, author, summary, or descriptionmatching `ObjectiveDropboxOfficial`

**Comment by scobbe** [comment]
@Moussy: The Objective-C SDK should be properly integrated with CocoaPods. Please run the following commands:

```
rm -rf ~/.cocoapods
pod setup
pod install

```

**Comment by Moussy** [comment]
@scobbe:  My cocoapod version is 1.1.0. Beta. 2, I can't search ObjectiveDropboxOfficial in cocoapods.
<img width="575" alt="f1249888-9afd-4542-9dae-ffa585472ce3" src="https://cloud.githubusercontent.com/assets/22519249/18983296/80ff09fc-871e-11e6-96b5-7f1a756605bb.png">
Are you sure I can pass cocoa pods import the SDK? Why I can't search in the cocoapods？
Thank you very much.

**Comment by scobbe** [comment]
@Moussy: Sometimes your local copy of the CocoaPods master repo can be corrupted.

Were you able to run `rm -rf ~/.cocoapods` to remove your local copy and `pod setup` to rebuild it?

If you did that, and you're still unable to search for `ObjectiveDropboxOfficial`, then please ensure that you're using the latest version of of CocoaPods by running the following command:

`gem install cocoapods`

I believe the issue is with your local environment. When I run `pod search ObjectiveDropboxOfficial`, I receive the following response:

```
-> ObjectiveDropboxOfficial (1.1.0)
   Dropbox Objective C SDK for APIv2
   pod 'ObjectiveDropboxOfficial', '~> 1.1.0'
   - Homepage: https://dropbox.com/developers/
   - Source:   https://github.com/dropbox/dropbox-sdk-obj-c.git
   - Versions: 1.1.0, 1.0.12, 1.0.11, 1.0.10, 1.0.9, 1.0.8, 1.0.6, 1.0.3, 1.0.1, 1.0.0 [master repo]
```

**Comment by Moussy** [comment]
@scobbe : My problem has been solved, thank you very much.
