### ISSUE TITLE
listFolderContinue - hasMore issue

### ISSUE THREAD

**Issue by ranapnea** [dropbox/dropbox-sdk-obj-c#45]
I have observed infinite loop when using listFolderContinue - call. In my code, I check for DBFILESListFolderResult instance ".hasMore" which returns YES and then pass the ".cursor" to the next call. The result is that I get the files but then I keep seeing hasMore = YES while "entries" is empty. The cursor value always changes from one call to another.

The expected behaviour was that when there are no more entries to receive, hasMore = NO.

Workaround: Continue only if hasMore = YES and entries is not empty.

This was found on Mac OSX Sierra.

**Comment by programmerbird** [comment]
Dropbox's `hasMore` is weirdly `NSNumber`. Not `BOOL` type. You will need to do something like this:

    BOOL hasMore = [cursor.hasMore boolValue];

**Comment by ranapnea** [comment]
Closing this one - my bad indeed. Did not check that hasMore is NSNumber type in this API.

**Comment by scobbe** [comment]
@programmerbird: Thanks for pointing this out.

We do use `NSNumber` objects to represent boolean values because sometimes we need to represent nullability with in our API results.

It's a bit of an awkward experience for the user of the SDK, though. I just added a [note](https://github.com/dropbox/dropbox-sdk-obj-c#handle-the-api-response) to the README about it.
