### ISSUE TITLE
header file not found

### ISSUE THREAD

**Issue by kalsky** [dropbox/dropbox-sdk-obj-c#47]
Hi

I tried to follow the guide on how to integrate into my project (using Carthage), but I'm stuck at the import line:
`#import <ObjectiveDropboxOfficial/ObjectiveDropboxOfficial.h>`
giving me an error that it cannot be found.

I saw this issue was fixed in 1.1.0 (and I checked the code that is downloaded when running the Carthage update command, and it looks like the above file is marked as public in the project), but it doesn't work.

using another import, like:
`#import <ObjectiveDropboxOfficial/DropboxClient.h>`
does work.

Thanks,
Yaniv

**Comment by scobbe** [comment]
@kalsky: Thanks for reaching out and sorry that you're running into issues. Can you confirm for me the following:

- you added the `.xcodeproj` file as a subproject, rather than as a separate workspace? (i.e. when you dragged and dropped the file, you should be sure that no window popped up prompting you to create another workspace)

- you performed a clean build in Xcode (cmd + option + shift + k)

- you added the `.framework` file as an **Embedded Binary** in your project, like this:

![image](https://cloud.githubusercontent.com/assets/17483354/19086818/9001e966-8a24-11e6-9841-d80bbddd52f3.png)

If you don't add as an embedded binary, your target won't be able to import the umbrella header.

Right now, importing as a subproject works for me, so if you can confirm that you completed the above steps, and you still have an issue, then would you mind sending me a redacted .zip file of your project so I can take a look further ?

**Comment by kalsky** [comment]
@scobbe thanks for your reply.
When using this method ("manually add subproject" as it is called in the instructions) it works.
But I was referring to the other method (under "Carthage" in the instructions) - I want to use just the framework, without having the subproject. So maybe something is missing in the documentation there.

Is there a meaningful difference between the 2 approaches?

**Comment by scobbe** [comment]
@kalsky: Oh, sorry, I misread. Hmm, I'm still able to successfully import v1.1.1 of the SDK after following the instructions under the "Carthage" section of the README, and with the following line in my code:

`#import <ObjectiveDropboxOfficial/ObjectiveDropboxOfficial.h>`

To answer your question, there is in fact a meaningful difference between importing the SDK as a subproject, and simply adding the `.framework` file to your project. Although both use Carthage, in the first case, you compile and build the SDK as part of your own project, whereas in the second case, you are simply adding a `.framework` file to your project. This is akin to adding a "black box" binary to your project, which you cannot modify or rebuild.

It should be clear why we use Carthage for distributing the `.framework` files (Carthage fetches the appropriately versioned source from GitHub, and builds the `.framework` file automatically. 

As far as using Carthage for adding the SDK as a subproject, the reason we do this is because you still need to fetch the GitHub code before you add it to your project. Carthage does this nicely, and it does it nicely within your project (which avoids a scenario where you do a `git clone...` outside of your project folder and you have all these project references that point to files external to the project folder).

Moreover, if the SDK has any third-party dependencies (say a third-party networking library), having Carthage pull these external repos into your project as well would be quite valuable.

For all these reasons, we advice that those who want to add the SDK as a subproject use Carthage to do so.

Does this clarify things at all?

Also, are you still having issues importing just the `.framework` file via Carthage? Did you follow all of the steps from the README, as well as debugging steps like full project clean (cmd + option + shift + k), ensure you added the `.framework` file to **Linked Frameworks and Libraries** etc?

**Comment by kalsky** [comment]
Thanks for the detailed explanation, it does make sense.
In my case, I'd like to use it as a black box, so I'm using the built .framework.
I managed to do the full project clean (cmd + option + shift + k), which is probably not the same as going to the project menu and use the clean option from there..
With the keyboard shortcut it cleaned it well and then it was able to find the umbrella header.

Thanks again,
Yaniv
