### ISSUE TITLE
Issue with Single Sign-On for Business Account Trial

### ISSUE THREAD

**Issue by shammatime** [dropbox/dropbox-sdk-obj-c#48]
When utilizing single sign-on, the authentication view that is displayed does nothing after the continue button is selected(a loading spinner is displayed and the button becomes in active). This occurs when the Dropbox application is not installed on the device forcing the sdk to use the internal authentication method. I have tested my use case with the Dropbox application and I am redirected correctly to my single sign-on provider and authentication is successful. Is this a known issue or not currently supported?

**Comment by greg-db** [comment]
Thanks for the report @shammatime . This should work, and I can't reproduce the behavior you're seeing. 

Once SSO is detected for the entered email address, the "Single sign-on enabled" text should be shown, with the "Continue" button underneath. Clicking that does successfully redirect me to the SSO provider I'm testing with (OneLogin).

What provider are you using? Are you still seeing this issue? It's possible the provider was just having some issues, as it sounds like it failed to load. (The "Continue" button is made inactive and the spinner is displayed while the request to load your provider's page is in progress.)

**Comment by shammatime** [comment]
Hey Greg,  thanks for the response. I am using Ping for my provider. The same Ping provider works fine when utilizing it with the Dropbox application.

Inside my application there are no errors in the console after I select continue. The dropbox authentication page just stays static. I though this might be an ATS issue but have disabled it in my application and it still does not work. Right now I am not sure how to proceed.

**Comment by scobbe** [comment]
@shammatime: Thanks for your reply. Would you mind confirming for us that you experience this problematic behavior both in the in-app webview auth flow, as well as the browser redirect auth flow?

That is, can you confirm that this behavior is exhibited when `browserAuth` is both `YES` and `NO` here:

```
[DropboxClientsManager authorizeFromController:[UIApplication sharedApplication]
                                        controller:self
                                           openURL:^(NSURL *url){ [[UIApplication sharedApplication] openURL:url]; }
                                       browserAuth:YES];
```

**Comment by shammatime** [comment]
Hey @scobbe,

I don't use the exact call as above. Here is my code
```obective-c
DBMobileSharedApplication *sharedMobileApplication = [[DBMobileSharedApplication alloc] init:[UIApplication sharedApplication]controller:viewControlleropenURL:^(NSURL *_Nonnull url) {
                                                                                                 NSError *error;
                                                                                                 DBAccessToken *accessToken = [self handleOpenUrl:url error:&error];
                                                                                                 authHandler(accessToken, error);
                                                                                             }];

[[DBOAuthManager sharedOAuthManager] 
authorizeFromSharedApplication:sharedMobileApplication browserAuth:YES];
```



I tried with 'browserAuth' set to 'YES'. The problem is nothing occurs when the value is 'YES'. If the value is 'NO', the authentication view(Inside my application) is displayed but I have the same problem as stated in my original post. This all occurs without the Dropbox application installed.

**Comment by scobbe** [comment]
@shammatime: Thanks for the code. I think it clears things up a little bit.

To begin, it appears that you're using the `openURL` closure as an auth response handler. That's not quite what it's for. The `openURL` closure is really just a wrapper around the sensitive `[[UIApplication sharedApplication] openURL:url]` call (which is not [app extension safe](https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html). By forcing the client to explicitly supply a reference to `openURL`, the SDK becomes "app extension safe".

It appears that because you have removed the `[[UIApplication sharedApplication] openURL:url];` call from the the `openURL` closure, it's no longer opening an external app on redirect. Try putting that line back in and see if that fixes anything.

Maybe what you should be doing is calling `authHandler(accessToken, error)` in you app delegate, once you retrieve the the auth token after the redirect, [like in the README](https://github.com/dropbox/dropbox-sdk-obj-c#handle-redirect-back-into-sdk).

Is there a reason you can't call your `authHandler` closure from the `application:handleOpenURL` in your app delegate? That way, you could use the code from the README (which I pasted above), which might be more convenient.

**Comment by scobbe** [comment]
@shammatime: Any update here? Did my comments make sense? I know I wrote a lot...

Are you still running into issues?

**Comment by shammatime** [comment]
@scobbe This can be closed for now. We are making some changes internally to our test IDP's so I am not currently able to test this. Thank you for your help.

**Comment by scobbe** [comment]
@shammatime: Ok, will do. If you end up having the same problem once you make the changes, please reach back out. Good luck!
