### ISSUE TITLE
How  to get all files in dropbox by DropboxClient?

### ISSUE THREAD

**Issue by Moussy** [dropbox/dropbox-sdk-obj-c#57]
Now I have the authority is successful, I need to call a method for current account all of the files, what should I do?
Thank you very much.

**Comment by greg-db** [comment]
Hi @Moussy you can use the [`listFolder`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESRoutes.html#/c:objc(cs)DBFILESRoutes(im)listFolder:recursive:includeMediaInfo:includeDeleted:includeHasExplicitSharedMembers:) (with `recursive`) and [`listFolderContinue`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESRoutes.html#/c:objc(cs)DBFILESRoutes(im)listFolderContinue:) to get a listing of all of the files and folders in the account. The [`listFolderContinue`](https://dropbox.github.io/dropbox-sdk-obj-c/api-docs/latest/Classes/DBFILESRoutes.html#/c:objc(cs)DBFILESRoutes(im)listFolderContinue:) method also lets you stay up to date over time by getting any new changes since you last called.

**Comment by Moussy** [comment]
@greg-db Thank you very much, I have got all files.
Now encountered a new problem, I need to give our service side preach a url, and then they via the url to get the file information, but Dropbox file list back, no I need the url.
My engineers are discussed, and the android they still use is DBChooser, but we use the last version DBChooser now has a problem, always pop up please install Dropbox.
1. If we still can use DBChoose？
2. If use Dropbox API v2, how can we get this url to our server？
Our app support ios 8.0 and above, support our demand is obtained from Dropbox document url uploaded to the server, the client does not do to download.

**Comment by greg-db** [comment]
@Moussy I'll be happy to help further, but I'm not sure I understand your questions.

You can still use the Dropbox Chooser, and if you're experiencing any issues with it, please share the details, e.g., your code and the steps to reproduce the issue, the version of the SDK and platform, etc. That's not on GitHub though, so feel free to open that as a thread on our forum: https://www.dropboxforum.com/t5/forums/postpage/board-id/101000014

For any other API question(s) you have, please also open a new GitHub issue on the relevant repo(s), or open a thread for each on the forum. Again, please include any code or steps to show the issue. 

Thanks in advance!

**Comment by Moussy** [comment]
@greg-db My problem has been solved, thank you very much.
