### ISSUE TITLE
Why are the namespaces of this Framework so terrible?

### ISSUE THREAD

**Issue by jkichline** [dropbox/dropbox-sdk-obj-c#75]
Maybe it's the OCD part of me, but this framework appears to be all over the place.  The framework is called ObjectiveDropboxOfficial.framework which is like the "Department of Redundancy Department".  Are you going to have another framework that supports Swift? Why not just call it Dropbox.framework or DropboxKit.framework?

Then some of the classes start with Dropbox while others start with DB and then you do some strange thing by making part of the framework it's own namespace like DBUSERS.  This makes the framework look amateur at best but has other implications as well.  Why not namespace EVERYTHING with a simple DB or DBO?

Honestly I don't even want to use this framework because I have a feeling that it's going to be crap just by looking at the inconsistencies in the naming convention.

**Comment by greg-db** [comment]
Thanks for the feedback! I'll make sure the team sees it.

For reference, I believe part of the naming is due to the existence of [this unofficial ObjectiveDropbox library](https://cocoapods.org/?q=ObjectiveDropbox), and yes, we do have [a Swift library](https://github.com/dropbox/SwiftyDropbox).

**Comment by scobbe** [comment]
@jkichline: Apologies for the delay in responding here. You bring up some good points. Our naming conventions were pretty confusing and bad. I think we were trying to keep a consistent naming experience across all our different supported languages (Obj-C, Swift, Java, C#, etc.), rather than adopting nice, consistent Obj-C standards.

That's changed somewhat with the latest version of the SDK (v3.0.0). Everything now has at least a DB prefix (rather than Dropbox or something else). We still keep the API namespace naming prefixes (like DBUSERS) because it really does improve readability for these autogenerated API datatypes (which we have hundreds of) and which span across like six namespaces.

We hope you'll give the framework a try! Thanks again for the feedback. Let us know if you have any other feedback.
