### ISSUE TITLE
How to cancel current operation(s)

### ISSUE THREAD

**Issue by SDPrio** [dropbox/dropbox-sdk-obj-c#85]
I am working on integration API v2 into my iOS 8+ app while it used the Core API (v1) before. 

The old API supported the cancellation of the current operation by calling `[restClient cancelAllRequests]` or by using `cancelFileLoad:` or `cancelFileUpload`. I was not able to find such a methods in the v2 API. 

How to cancel operations in API v2?

**Comment by greg-db** [comment]
The API v2 Objective-C SDK doesn't have a method like `cancelAllRequests` to cancel all active requests at once, but I'll be sure to pass this along as a feature request. 
 
When using upload sessions though, since you control how and when each portion is uploaded, you can have your app stop the upload session by stopping further calls.
 
And in any case, you can cancel an individual upload call (when using upload sessions or not) by calling cancel on the task object itself, like this:

 ```
DBUploadTask *req = [client.filesRoutes upload...
[req cancel];
```

(Note that there's a bug with that in [2.0.6](https://github.com/dropbox/dropbox-sdk-obj-c/issues/76), so you may want to use 2.0.5 for now to do this.)
