### ISSUE TITLE
listFolderLongpoll:timeout: times out prematurely due to default timeoutIntervalForRequest

### ISSUE THREAD

**Issue by martinoneutrino** [dropbox/dropbox-sdk-obj-c#98]
The configuration of the default `NSURLSessionConfiguration` `timeoutIntervalForRequest` to 60 seconds (in `DBTransportClient` init) causes `DBFILESRoutes listFolderLongpoll:timeout:` to prematurely timeout with a _NSURLErrorDomain Code=-1001 ("The request timed out.")_, even though the longpoll request timeout is valid up to 480 seconds.

**Comment by greg-db** [comment]
Thanks for the report! We'll look into it.

**Comment by scobbe** [comment]
@martinoneutrino: Thanks for bringing this issue up. It should be fixed by 052c961, which will be included in the next release, which should land in the next day or two.

Please note, because of an [iOS 10 bug](https://github.com/dropbox/dropbox-sdk-obj-c#longpoll-session-timeout-bug), we only support a timeout period of up to 300 seconds on iOS 10, until Apple fixes the bug.

Let us know if anything else comes up!
